services:
  #If you need replicas of the containers, copy and past. At this moment,
  #DockerComposeV2's "replica" does not work as DockerComposeV1's
  frontend:
    container_name: frontend
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - keycloak
  #    - nodebackend
  #    - springbackend

  nginx:
    container_name: middlenginx
    image: nginx:stable-alpine
    expose:
      - "80"
    ports:
      - "80:80"
    volumes:
      #- ./matomo:/var/www/html:z,ro
      - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
      #- ./matomo.conf:/etc/nginx/conf.d/default.conf:z,ro
    depends_on:
      - nodebackend
      - springbackend

  #nodebackend:
  #  container_name: nodebackend
  #  build:
  #    context: ./node-backend
  #    dockerfile: ./Dockerfile
  #  volumes:
  #    - .:/usr/app/
  #    - /usr/app/node_modules
  #  ports:
  #    - "3000:3000"
  #  expose:
  #    - "3000"
  #  depends_on:
  #    - keycloak

  #springbackend:
  #  container_name: springbackend
  #  restart: always
  #  build:
  #    context: ./java-backend
  #    dockerfile: ./Dockerfile
    #volumes:
    #  - .:/usr/app/
    #  - /usr/app/node_modules
  #  ports:
  #    - "4000:4000"
  #  expose:
  #    - "4000"
  #  depends_on:
  #    - keycloak

  #postgres:
  #  image: postgres:14.1-alpine
  #  restart: always
  #  volumes:
  #    - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
  #  expose:
  #    - "7432"
  #  ports:
  #    - '7432:7432'
  #  env_file:
  #    - ./database.dev.env
    #healthcheck:
    #  test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 5
  #  command: -p 7432

#https://www.youtube.com/watch?v=_0oXZKr97ro
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:legacy
    env_file:
      - ./keycloak.dev.env
    volumes:
      - ./keycloak-themes/school/:/opt/jboss/keycloak/themes/school/
      - ./keycloak-themes/keywind/:/opt/jboss/keycloak/themes/keywind/
    command: ["-Djboss.http.port=8180"]
    ports:
      - "8180:8180"
    expose:
      - "8180"
    depends_on:
      - postgres

